#title: Intelligibly Intelligent
#description: Machine Learning
#google_analytics: 
#show_downloads: false
#theme: jekyll-theme-tactile

#gems:
#  - jekyll-mentions

name: Ranjan K. Maji
markdown: kramdown
